### DISCUSSION TITLE
Setting desired temperature from HA

### DISCUSSION THREAD

**Discussion by spotpkt** [jlvaillant/intellicenter#24] [Ideas]
I've built a lovelace card where I can adjust my 'desired temperature' for both the pool and the spa.  Where I'm struggling is how to push that value to the intellicenter to set that temperature.

My understanding is that because the desired temperature is set up as a switch on the integration, there isn't a function to set the value.  Is it possible to add a thermostat value that could be pushed to the intellicenter?  

Hopefully what I'm trying to do makes sense.

Thanks in advance!

```
pooltempslider:
    name: Pool Temperature goal
    initial: 78
    min: 55
    max: 92
    step: 1
        
  spatempslider:
    name: Spa Temperature goal
    initial: 94
    min: 88
    max: 104
    step: 1
```

```
type: entities
entities:
  - entity: input_number.pooltempslider
  - entity: input_number.spatempslider
state_color: false
```

**Comment by dwradcliffe** [comment]
The desired temperature is not a switch, it's a `water_heater`. You should see a water heater entity (or multiple) in the list of entities from this integration.

Here's mine:
![image](https://user-images.githubusercontent.com/118850/126661014-60bfb145-8e2d-48a3-8554-b847fe5869fa.png)

As for the UI, I haven't yet found a way to have a slider directly for the water_heater so it may be necessary to have an input_number and use an automation to "transfer" the value from that to the water_heater entity. You'll need to use the `water_heater.set_temperature` service. This is actually on my todo list too, so if I get it to work I'll post back here.

**Reply by spotpkt** [reply]
Ahh okay.  I'll try to play around with it some this weekend to see if I can grab that input_number and apply it to water_heater.  If I can get it working, I'll put my yaml up here.  Thanks for the follow-up.

**Reply by abenedet78** [reply]
I can confirm I got this working in Lovelace. Here's what I did:

1. Created a text input helper
2. Added this to Lovelace as a slider
3. Created an automation that is triggered by this text input and then used the "water_heater.set_temperature"  service to set the temperature to the inputted text value from the slider. 

Works instantaneously and triggers the heater right away. 

Note I'm quite a noob but I got this to work.

**Reply by spotpkt** [reply]
It's been a while, but I had a chance to work on this some more.  Your method worked perfectly.  For anyone else trying to replicate, here is a compact lovelace example and yaml for the automation.  This doesn't turn on the heater, but you can do that with the toggle on the lovelace side.

```
type: entities
entities:
  - entity: input_number.pooltempslider
  - entity: input_number.spatempslider
state_color: true
header:
  type: buttons
  entities:
    - entity: switch.pool
      tap_action:
        action: more-info
      hold_action:
        action: toggle
      name: Pool
    - entity: water_heater.pool
      tap_action:
        action: none
      hold_action:
        action: toggle
    - entity: switch.spa
      tap_action:
        action: more-info
      hold_action:
        action: toggle
      name: Spa
    - entity: water_heater.spa
      hold_action:
        action: toggle
      tap_action:
        action: none
```


And here is the automation:
``` alias: Set Spa Temperature
description: ''
trigger:
  - platform: state
    entity_id: input_number.spatempslider
condition: []
action:
  - service: water_heater.set_temperature
    target:
      entity_id: water_heater.spa
    data:
      temperature: '{{ states(''input_number.spatempslider'') | int}}'
mode: single 
```


Pool is the same, just changing the variables.
