### ISSUE TITLE
Sliders for pool temperature

### ISSUE THREAD

**Issue by rsnodgrass** [jlvaillant/intellicenter#21]
Would like to figure out how to add bounded temperature setting sliders (or other) to the heaters.  Presumably since these are water_heaters there is a common way to do this.  I'd leave the minimum setting to 32, since freeze protection would effectively switch on the heaters anyway at 32.

For my pool, I have the sliders set to a max of 85 degrees F, while the spa at 104 degrees F.

I haven't investigated yet, other than create Lovelace mockup of the sliders:

![image](https://user-images.githubusercontent.com/2199132/120902600-14693d00-c5f6-11eb-824d-0ffb158ded9b.png)

Anyway, adding this as a placeholder.

**Comment by rsnodgrass** [comment]
Just for reference, my Lovelace:

```yaml
type: entities
entities:
  - entity: light.landscape_light
    type: custom:multiple-entity-row
    name: Lights
    state_header: Landscape
    toggle: true
    state_color: true
    entities:
      - entity: light.pool_light
        name: Pool
        toggle: true
  - label: Pool
    type: section
  - entity: input_boolean.pool_safety_alarm
    type: custom:multiple-entity-row
    name: Pool Heater
    state_header: ''
    toggle: true
    state_color: true
    icon: mdi:coolant-temperature
    entities:
      - entity: sensor.pool_last_temp
        name: Last Temp
      - entity: sensor.pool_desired_temp
        name: Desired
  - entity: switch.stairs_main_lights
    name: Waterfall *
  - label: Spa
    type: section
  - entity: input_boolean.pool_safety_alarm
    type: custom:multiple-entity-row
    name: Spa Heater
    state_header: ''
    toggle: true
    state_color: true
    icon: mdi:coolant-temperature
    entities:
      - entity: sensor.spa_last_temp
        name: Last Temp
      - entity: sensor.spa_desired_temp
        name: Desired
  - entity: input_number.spa_temp_slider
    name: Spa Temp Setting
  - label: Safety
    type: section
  - entity: input_boolean.pool_safety_alarm
    name: Child Safety Alarm
  - entity: binary_sensor.ring_side_motion
    name: Pool Area Occupied
show_header_toggle: false
```

**Comment by rsnodgrass** [comment]
I have a simple water header card that could be used, but wanted an even simpler slider:

https://github.com/rsnodgrass/water-heater-card

```yaml
input_number:                                                                                                                                                                                    
  pool_temp_slider:                                                                                     
    name: "Pool Temp Setting"                                                                           
    unit_of_measurement: "°F"                                                                           
    icon: mdi:thermometer                                                                               
    initial: 85                                                                                         
    min: 32                                                                                             
    max: 85                                                                                             
    step: 1                                                                                             
                                                                                                        
  spa_temp_slider:                                                                                      
    name: "Spa Temp Setting"                                                                            
    unit_of_measurement: "°F"                                                                           
    icon: mdi:thermometer                                                                               
    initial: 104                                                                                        
    min: 32                                                                                             
    max: 104                                                                                            
    step: 1
```
